version: '3.9'
services:
  elastic_kibana:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch #имя ноды
      - cluster.name=es-cluster-7 #имя кластера
      - discovery.type=single-node #кластер только из одной ноды
      - xpack.security.enabled=true #включаем базовые сервисы безопасности
      - xpack.security.authc.api_key.enabled=true #включаем доступ по API ключам
      - ELASTIC_PASSWORD=password #задаем пароль для встроенного юзера elastic
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #оверрайдим размер кучи на 512мб, иначе начинает есть всю оперативку
    volumes:
    - elastic_kibana-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: kibana:7.14.0
    container_name: kibana
    environment:
     - SERVER_HOST=0.0.0.0
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     - ELASTICSEARCH_USERNAME=elastic
     - ELASTICSEARCH_PASSWORD=password
    ports:
      - 5601:5601
    networks:
      - es-network
        

volumes:
  elastic_kibana-data:
    driver: local

networks:
  es-network:
    driver: bridge
